#!/bin/bash

set -ex

index=${1:-0}
name=${2:-Debug/lean-ftl-u5a5.elf}
addr=${3:-0x08000000}
#power cycle to make any latent change to option bytes visible
STM32_Programmer_CLI --connect port=swd index=${index} -halt --power off index=${index} --power on index=${index}
STM32_Programmer_CLI --connect port=swd index=${index} -halt --optionbytes displ -ob SWAP_BANK=0 --erase all --download ${name} ${addr} --start