#!/bin/bash

set -ex

VERSION=${1:-v0.0.10}
DISTDIR=lean-ftl-dist

rm -rf $DISTDIR
mkdir $DISTDIR
cd $DISTDIR
wget https://github.com/sebastien-riou/lean-ftl/releases/download/${VERSION}/lean-ftl-${VERSION}.tar.gz
tar -xf lean-ftl-${VERSION}.tar.gz
mv dist/liblean-ftl-test . 
tar -xf dist/liblean-ftl-minSizeRel.tar.gz
mv liblean-ftl minSizeRel
